// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22.03.2026, 12:34:42
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/projects/digital-twin-planner/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/digital-twin-planner/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/digital-twin-planner/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/digital-twin-planner/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/digital-twin-planner/app/plugins/**/*.{js,ts,mjs}","C:/projects/digital-twin-planner/app/composables/**/*.{js,ts,mjs}","C:/projects/digital-twin-planner/app/utils/**/*.{js,ts,mjs}","C:/projects/digital-twin-planner/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/digital-twin-planner/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/projects/digital-twin-planner/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/projects/digital-twin-planner/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;